### ISSUE TITLE
empty entry submission

### ISSUE THREAD

**Issue by samsmith** [openhealthcare/whopaysthisdoctor.org#12]
if there's an update that day, do not display an empty entry.
If there wasn't another update that day, simply say there was a null declaration made.

This will require iteration over time.

**Comment by davidmiller** [comment]
I'm not sure I know what this means? Do you have steps to reproduce / screenshots?

**Comment by davidmiller** [comment]
As I understand it you can't actually submit an empty declaration - you'd have to enter dummy text to get past the form validation.

I suspect this goes away with #29 and #21 e.g. one declaration per calendar year, and make your declarations editable.
