### ISSUE TITLE
Remove default vale from Benefit.band widget

### ISSUE THREAD

**Issue by samsmith** [openhealthcare/whopaysthisdoctor.org#25]
the financial bands offered in the declaration dropdowns should not include a "--------" item in the list (which people think is a valid entry, but which fails validation and they get confused by the messages).  (any fieldset triples which have a financial value but no other field entry should be ignored)

**Comment by davidmiller** [comment]
The relevant Django forms incantation is something like `empty_label=None` I think...

**Comment by davidmiller** [comment]
I think this goes away with the new declaration format - there's no band field.
