### ISSUE TITLE
Edit existing declarations 

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/whopaysthisdoctor.org#29]
Not sure there's currently a way to edit a declaration?

Seems like an obvious thing to want.

**Comment by samsmith** [comment]
> On 1 Jul 02019, at 16:27, David Miller <notifications@github.com> wrote:
> 
> Not sure there's currently a way to edit a declaration?
> 
> Seems like an obvious thing to want
> 

Declarations are made at points in time. 

You can say your past declaration is no longer applicable etc, but can’t edit the past.

**Comment by davidmiller** [comment]
People make typos.
The whole thing is based on trusting people to write stuff down honestly.
Anything else adds quite a lot of complexity to the UI / experience / implementation.

**Comment by davidmiller** [comment]
Far from convinced this is coherent, but suspect it just doesn't matter. Let's not for now.
